trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  persistCredentials: true

- script: |
    git push --prune https://$(System.AccessToken)@dev.azure.com/Hefestos/Tons%20Personalizados/_git/tons-backend +refs/remotes/origin/*:refs/heads/*
  displayName: 'Espelhar GitHub para Azure DevOps'