trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  persistCredentials: true

- script: |
    git remote add target https://$(System.AccessToken)@dev.azure.com/Hefestos/Tons%20Personalizados/_git/tons-backend
    git push target main --force
  displayName: 'Sincronizar GitHub -> Azure'